# Site settings
title: Vikas Srivastava
author:
  name: Vikas Srivastava
  email: vsv@nitw.ac.in
description: "Personal Website"


# generate social links in footer
social_links:
   linkedin: 
   facebook: 

minima:
  skin: classic

# Build settings
remote_theme: jekyll/minima
#theme: jekyll/leap-day  
#theme: minima
#remote_theme: jekyll-theme-slate
#  skin: dark

  
